#!/usr/bin/env node
/**
 * Seed a local (or remote) D1 database with one working cell.
 *
 * Everything this creates is an *example* organisation, not church policy.
 * District / area / zone names, meeting times and the welcome message are all
 * ordinary data that a leader edits from the app — nothing about how a real
 * Loveworld / Christ Embassy structure must be named is baked in here.
 *
 * Passwords are hashed with the same PBKDF2-HMAC-SHA256 parameters the Worker
 * uses, so the seeded accounts can log in normally.
 *
 *   node worker/scripts/seed.mjs              # local
 *   node worker/scripts/seed.mjs --remote     # deployed database
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { webcrypto as crypto } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const WORKER_DIR = resolve(HERE, '..');
const REMOTE = process.argv.includes('--remote');
/** Wipe every table before seeding, so a test run starts from a known state. */
const RESET = process.argv.includes('--reset');

/**
 * Deletion order matters: children before parents. Listed explicitly rather
 * than discovered, so a new table that is added later must be considered here
 * deliberately instead of being silently left behind.
 */
const TABLES_IN_DELETION_ORDER = [
  'consent_records',
  'notifications',
  'testimonies',
  'prayer_requests',
  'follow_up_notes',
  'follow_ups',
  'attendance_records',
  'weekly_reports',
  'announcement_reads',
  'announcements',
  'material_acks',
  'materials',
  'invitations',
  'sessions',
  'audit_logs',
  'rate_limits',
  'users',
  'homecells',
  'zones',
  'areas',
  'districts',
  'organizations',
];

const ITERATIONS = 100_000;

function toBase64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

async function hashPassword(password, salt) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey('raw', enc.encode(password), { name: 'PBKDF2' }, false, [
    'deriveBits',
  ]);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: enc.encode(salt), iterations: ITERATIONS, hash: 'SHA-256' },
    key,
    256,
  );
  return toBase64(new Uint8Array(bits));
}

function randomSalt() {
  const buf = new Uint8Array(16);
  crypto.getRandomValues(buf);
  return toBase64(buf);
}

/** Single-quote escaping for SQL literals. */
function q(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

const NOW = '2026-01-01T00:00:00Z';

// ---------------------------------------------------------------------------
// The example cell. Change these freely — they are data, not doctrine.
// ---------------------------------------------------------------------------
const ORG = { id: 'org1', name: 'Example Church', code: 'EX1' };
const DISTRICT = { id: 'd1', name: 'Example District', code: 'D1' };
const AREA = { id: 'a1', name: 'Example Area', code: 'A1' };
const ZONE = { id: 'z1', name: 'Example Zone', code: 'Z1' };

const CELL = {
  id: 'hc1',
  name: 'Grace Life Online Cell',
  code: 'HC1',
  meetingDay: 'sunday',
  meetingTime: '18:00',
  timezone: 'Africa/Lagos',
  platform: 'google_meet',
  description:
    'A small online community of believers who meet every Sunday evening to grow in the Word and look out for one another.',
  welcome:
    'Wherever you are joining from, there is a place for you here. We meet weekly to pray, study the Word and encourage one another.',
};

/**
 * Accounts.
 *
 * `passwordEnv` names the environment variable that overrides the default, so a
 * real deployment never ships with a documented password. The defaults are for
 * local development and are printed so a developer can log in immediately.
 */
const ACCOUNTS = [
  {
    id: 'u1',
    name: 'Pastor John',
    phone: '+2348051112222',
    role: 'leader',
    isCellLeader: true,
    passwordEnv: 'SEED_LEADER_PASSWORD',
    defaultPassword: 'GraceLife2026!',
  },
  {
    id: 'u2',
    name: 'Blessing Adeyemi',
    phone: '+2348123456789',
    role: 'member',
    isCellLeader: false,
    passwordEnv: 'SEED_MEMBER_PASSWORD',
    defaultPassword: 'Member2026!',
  },
];

async function buildSql() {
  const lines = [];

  lines.push('-- Generated by worker/scripts/seed.mjs — safe to re-run.');
  lines.push('PRAGMA foreign_keys = OFF;');
  lines.push('');

  if (RESET) {
    lines.push('-- Wipe first, so the result is identical regardless of what ran before.');
    for (const table of TABLES_IN_DELETION_ORDER) {
      lines.push(`DELETE FROM ${table};`);
    }
    lines.push('');
  }

  // Organisational shell.
  lines.push(`INSERT OR IGNORE INTO organizations (id, name, slug, created_at, updated_at)
  VALUES (${q(ORG.id)}, ${q(ORG.name)}, ${q(ORG.code)}, ${q(NOW)}, ${q(NOW)});`);
  lines.push(`INSERT OR IGNORE INTO districts (id, organization_id, name, code, created_at, updated_at)
  VALUES (${q(DISTRICT.id)}, ${q(ORG.id)}, ${q(DISTRICT.name)}, ${q(DISTRICT.code)}, ${q(NOW)}, ${q(NOW)});`);
  lines.push(`INSERT OR IGNORE INTO areas (id, district_id, name, code, created_at, updated_at)
  VALUES (${q(AREA.id)}, ${q(DISTRICT.id)}, ${q(AREA.name)}, ${q(AREA.code)}, ${q(NOW)}, ${q(NOW)});`);
  lines.push(`INSERT OR IGNORE INTO zones (id, area_id, name, code, created_at, updated_at)
  VALUES (${q(ZONE.id)}, ${q(AREA.id)}, ${q(ZONE.name)}, ${q(ZONE.code)}, ${q(NOW)}, ${q(NOW)});`);

  // The cell is created before the people who belong to it, because a user row
  // references its homecell. The leader is attached afterwards.
  lines.push(`INSERT INTO homecells
    (id, zone_id, name, code, meeting_day, meeting_time, timezone, meeting_platform,
     description, welcome_message, absence_threshold, auto_approve_members,
     public_join_enabled, is_active, leader_id, created_at, updated_at)
  VALUES (${q(CELL.id)}, ${q(ZONE.id)}, ${q(CELL.name)}, ${q(CELL.code)},
          ${q(CELL.meetingDay)}, ${q(CELL.meetingTime)}, ${q(CELL.timezone)}, ${q(CELL.platform)},
          ${q(CELL.description)}, ${q(CELL.welcome)}, 2, 1, 0, 1, NULL,
          ${q(NOW)}, ${q(NOW)})
  ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    meeting_day = excluded.meeting_day,
    meeting_time = excluded.meeting_time,
    timezone = excluded.timezone,
    meeting_platform = excluded.meeting_platform,
    description = excluded.description,
    welcome_message = excluded.welcome_message,
    auto_approve_members = excluded.auto_approve_members,
    updated_at = excluded.updated_at;`);

  // Accounts, hashed exactly as the Worker does.
  const credentials = [];
  for (const account of ACCOUNTS) {
    const password = process.env[account.passwordEnv] ?? account.defaultPassword;
    const salt = randomSalt();
    const hash = await hashPassword(password, salt);
    credentials.push({ ...account, password });

    lines.push(`INSERT INTO users
      (id, homecell_id, name, phone, role, status, member_status, membership_type,
       is_first_timer, password_hash, password_salt, password_iterations,
       joined_date, created_at, updated_at)
    VALUES (${q(account.id)}, ${q(CELL.id)}, ${q(account.name)}, ${q(account.phone)},
            ${q(account.role)}, 'active', ${q(account.role === 'leader' ? 'member' : 'first_timer')},
            'old_member', 0, ${q(hash)}, ${q(salt)}, ${ITERATIONS},
            '2026-01-01', ${q(NOW)}, ${q(NOW)})
    ON CONFLICT(id) DO UPDATE SET
      password_hash = excluded.password_hash,
      password_salt = excluded.password_salt,
      password_iterations = excluded.password_iterations,
      updated_at = excluded.updated_at;`);
  }

  // Now that the leader's user row exists, make them the cell's leader.
  const leaderAccount = ACCOUNTS.find((a) => a.isCellLeader);
  lines.push(
    `UPDATE homecells SET leader_id = ${q(leaderAccount.id)} WHERE id = ${q(CELL.id)};`,
  );

  // Registration needs to know which cell a self-registering person joins when
  // they arrive without an invitation link. Without this setting they are
  // created with no cell and most of the app is closed to them.
  lines.push(`INSERT INTO app_settings (key, value, updated_at)
  VALUES ('default_homecell_id', ${q(CELL.id)}, ${q(NOW)})
  ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at;`);

  return { sql: lines.join('\n'), credentials };
}

async function main() {
  const { sql, credentials } = await buildSql();

  // Wrangler needs a real file path; it will not read SQL from stdin.
  const dir = mkdtempSync(join(tmpdir(), 'homecell-seed-'));
  const file = join(dir, 'seed.sql');
  writeFileSync(file, sql, 'utf8');

  execFileSync(
    'npx',
    ['wrangler', 'd1', 'execute', 'homecell-db', REMOTE ? '--remote' : '--local', '--file', file],
    { cwd: WORKER_DIR, stdio: 'inherit' },
  );

  console.log('\n\x1b[32m✓\x1b[0m Seed applied.\n');
  console.log('   Cell:      %s (%s)', CELL.name, CELL.code);
  console.log('   Public:    /cell/%s', CELL.code);
  console.log('\n   Sign-in accounts (local development only):');
  for (const c of credentials) {
    console.log(`     ${c.role.padEnd(8)} ${c.phone.padEnd(16)} ${c.password}`);
  }
  console.log(
    '\n   Override these with %s / %s before seeding anything real.\n',
    'SEED_LEADER_PASSWORD',
    'SEED_MEMBER_PASSWORD',
  );
}

main().catch((err) => {
  console.error('\n\x1b[31m✗\x1b[0m Seed failed:', err.message);
  process.exit(1);
});
